import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'services',
        path: '/services',
        title: 'Services',
        translateKey: 'nav.services',
        icon: 'services',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'workers',
        path: '/workers',
        title: 'Find Workers',
        translateKey: 'nav.workers',
        icon: 'workers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'cart',
        path: '/cart',
        title: 'Cart',
        translateKey: 'nav.cart',
        icon: 'cart',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'customerMenu',
        path: '',
        title: 'Customer',
        translateKey: 'nav.customerMenu.customerMenu',
        icon: 'customer',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'customerMenu.quote',
                path: '/quote',
                title: 'Request Quote',
                translateKey: 'nav.customerMenu.quote',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'customerMenu.feedback',
                path: '/feedback',
                title: 'Feedback & Loyalty',
                translateKey: 'nav.customerMenu.feedback',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminMenu',
        path: '',
        title: 'Admin',
        translateKey: 'nav.adminMenu.adminMenu',
        icon: 'admin',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin'],
        subMenu: [
            {
                key: 'adminMenu.dashboard',
                path: '/admin',
                title: 'Admin Dashboard',
                translateKey: 'nav.adminMenu.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'adminMenu.inventory',
                path: '/inventory',
                title: 'Inventory',
                translateKey: 'nav.adminMenu.inventory',
                icon: 'inventory',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'adminMenu.settings',
                path: '/admin/settings',
                title: 'Admin Settings',
                translateKey: 'nav.adminMenu.settings',
                icon: 'settings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'adminMenu.clients',
                path: '/admin/clients',
                title: 'Clients & History',
                translateKey: 'nav.adminMenu.clients',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'infoMenu',
        path: '',
        title: 'Information',
        translateKey: 'nav.infoMenu.infoMenu',
        icon: 'info',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'infoMenu.about',
                path: '/about',
                title: 'About Us',
                translateKey: 'nav.infoMenu.about',
                icon: 'about',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'infoMenu.contact',
                path: '/contact',
                title: 'Contact',
                translateKey: 'nav.infoMenu.contact',
                icon: 'contact',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'infoMenu.enterprise',
                path: '/enterprise',
                title: 'Enterprise',
                translateKey: 'nav.infoMenu.enterprise',
                icon: 'enterprise',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
